apiVersion: v1
kind: Endpoints
metadata:
  labels:
    release: prometheus
  name: node-exporter-lst
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.0.1.4
    nodeName: aksvm
  ports:
  - name: metrics
    port: 9100
    protocol: TCP